apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fellow-eagle-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fellow-eagle-nodejs 
  name: fellow-eagle-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fellow-eagle-nodejs 
